// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVfBaod7mvslY5zcv8cxMFey1Gqf90b2M',
    appId: '1:468085241140:web:97b44422ff32435bc12161',
    messagingSenderId: '468085241140',
    projectId: 'easyscan-e9dd0',
    authDomain: 'easyscan-e9dd0.firebaseapp.com',
    storageBucket: 'easyscan-e9dd0.appspot.com',
    measurementId: 'G-FVKRS55S9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP18T3HmwLYb21Ac2ozREfPX8Gz4S8axo',
    appId: '1:468085241140:android:490c7111012a2d60c12161',
    messagingSenderId: '468085241140',
    projectId: 'easyscan-e9dd0',
    storageBucket: 'easyscan-e9dd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB448mE66zJEPoO0FIZ8PsxE44KuMcg9Nw',
    appId: '1:468085241140:ios:260d24a5d216e5f4c12161',
    messagingSenderId: '468085241140',
    projectId: 'easyscan-e9dd0',
    storageBucket: 'easyscan-e9dd0.appspot.com',
    iosBundleId: 'com.example.easyscan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB448mE66zJEPoO0FIZ8PsxE44KuMcg9Nw',
    appId: '1:468085241140:ios:260d24a5d216e5f4c12161',
    messagingSenderId: '468085241140',
    projectId: 'easyscan-e9dd0',
    storageBucket: 'easyscan-e9dd0.appspot.com',
    iosBundleId: 'com.example.easyscan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVfBaod7mvslY5zcv8cxMFey1Gqf90b2M',
    appId: '1:468085241140:web:1a546c0905e72bb1c12161',
    messagingSenderId: '468085241140',
    projectId: 'easyscan-e9dd0',
    authDomain: 'easyscan-e9dd0.firebaseapp.com',
    storageBucket: 'easyscan-e9dd0.appspot.com',
    measurementId: 'G-NLK37S66DZ',
  );
}
